sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

branches:
  only:
  - master
  - feature/adapt-to-yarpOpenPose
  - feature/add-avoidance-module

install:
  - cd ..

  - git clone https://github.com/robotology/yarp.git
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCREATE_LIB_MATH=TRUE ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/icub-main.git
  - cd icub-main
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/icub-contrib-common.git
  - cd icub-contrib-common
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/kinect-wrapper.git
  - cd kinect-wrapper
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install
  - cd ../../

  - git clone https://github.com/robotology/icub-hri.git
  - cd icub-hri
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install
  - cd ../../

  - cd skeleton3D

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

notifications:
  email:
  - phuong.nguyen@iit.it
  - ph17dn@gmail.com
